/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  galerie: [
     {
       type: 'autogenerated',
       dirName: 'galerie', // Spécifiez le dossier "galerie" comme source
     },
  ],
  bibliotheque: [
    {
      type: 'autogenerated',
      dirName: 'bibliotheque', // Spécifiez le dossier "bibliotheque" comme source
    },
 ],

  installation: [
     {
       type: 'autogenerated',
       dirName: 'installation', // Spécifiez le dossier "installation" comme source
     },
  ],
 };
 
 export default sidebars;
 