/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  D: [
     {
       type: 'autogenerated',
       dirName: 'comprendre', // Spécifiez le dossier "comprendre" comme source
     },
  ],
  I: [
    {
      type: 'autogenerated',
      dirName: 'installer', // Spécifiez le dossier "installer" comme source
    },
 ],
  B: [
    {
      type: 'autogenerated',
      dirName: 'bib', // Spécifiez le dossier "langages" comme source
    },
 ],
};
 
 export default sidebars;
 